apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      restartPolicy: Always
      containers:
      - name: customers
        image: cluster-registry:32000/customers:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: database_uri
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            cpu: "0.20"
            memory: "128Mi"
          requests:
            cpu: "0.10"        
            memory: "64Mi"
            
